export const services = [
  {
    num: "001",
    name: "Web Development",
    desc: "Modern, responsive, and user-friendly websites designed to engage visitors and drive conversions.",
    coverImg:
      "https://images.pexels.com/photos/40185/mac-freelancer-macintosh-macbook-40185.jpeg",
    tags: [
      "High-performance websites",
      "Dashboards",
      "SaaS Applications",
      "Clean Architecture",
      "SEO Fundamentals",
      "Fast Load Times",
      "Responsive Web Design",
      "Frontend Development",
      "Backend Integration",
      "API Development",
      "Performance Optimization",
    ],
  },
  {
    num: "002",
    name: "App Development",
    desc: "Cross-platform apps for Android & iOS, developed with React Native for a smooth user experience.",
    coverImg: "https://images.pexels.com/photos/15092/pexels-photo.jpg",
    tags: [
      "Cross-platform apps",
      "Android & iOS",
      "React Native Development",
      "Smooth User Experience",
      "Offline Support",
      "Scalable Architecture",
      "API Integrations",
      "State Management",
      "Push Notifications",
      "Performance Optimization",
      "App Store Deployment",
    ],
  },
  {
    num: "003",
    name: "AI & Automation",
    desc: "AI Chatbots, AI Agents, and Workflow Automation for intelligent and automated processes.",
    coverImg:
      "https://images.pexels.com/photos/20870797/pexels-photo-20870797.jpeg",
    tags: [
      "AI Chatbots",
      "AI Agents",
      "Workflow Automation",
      "Data Enrichment",
      "Smart Features",
      "Process Optimization",
      "LLM Integrations",
      "Custom AI Pipelines",
      "Automation Scripts",
      "API Orchestration",
      "Monitoring & Analytics",
    ],
  },
  {
    num: "004",
    name: "Cloud & Backend",
    desc: "Robust APIs, Authentication & Authorization, Database Design, Caching Strategies, Observability & Logging, Scalable Architecture, Cloud Infrastructure, Serverless Functions, API Security, Performance Optimization, Deployment & Monitoring.",
    coverImg:
      "https://images.pexels.com/photos/374559/pexels-photo-374559.jpeg",
    tags: [
      "Robust APIs",
      "Authentication & Authorization",
      "Database Design",
      "Caching Strategies",
      "Observability & Logging",
      "Scalable Architecture",
      "Cloud Infrastructure",
      "Serverless Functions",
      "API Security",
      "Performance Optimization",
      "Deployment & Monitoring",
    ],
  },
  {
    num: "005",
    name: "eCommerce",
    desc: "E-commerce solutions for online stores, including product catalogs, payment integrations, and order management.",
    coverImg:
      "https://images.pexels.com/photos/35560482/pexels-photo-35560482.jpeg",
    tags: [
      "Custom Online Stores",
      "Product Catalogs",
      "Payment Integrations",
      "Order Management",
      "Checkout Workflows",
      "Analytics & Tracking",
      "Cart & Checkout UX",
      "Payment Gateways",
      "Inventory Management",
      "Third-Party Integrations",
      "Performance Optimization",
    ],
  },
  {
    num: "006",
    name: "Digital Marketing",
    desc: "Digital marketing strategies and campaigns to promote products and services online, including SEO, PPC, and social media marketing.",
    coverImg:
      "https://images.pexels.com/photos/7693201/pexels-photo-7693201.jpeg",
    tags: [
      "SEO & Search Rankings",
      "Social Media Marketing",
      "Google & Meta Ads",
      "Content Marketing",
      "Email Campaigns",
      "Brand Strategy",
      "PPC Campaign Management",
      "Analytics & Reporting",
      "Conversion Optimization",
      "Lead Generation",
      "Marketing Automation",
    ],
  },
  {
    num: "007",
    name: "Custom AI & Development",
    desc: "Custom AI models and development services to build intelligent and scalable AI solutions for your business.",
    coverImg:
      "https://images.pexels.com/photos/20870797/pexels-photo-20870797.jpeg",
    tags: [
      "Custom AI Models",
      "LLM Fine-Tuning",
      "RAG Pipelines",
      "AI Consulting",
      "Proof of Concept",
      "Production Deployment",
    ],
  },
  {
    num: "008",
    name: "Agentic Automation Architecture",
    desc: "Agentic automation architecture to build scalable and intelligent automation workflows for your business.",
    coverImg:
      "https://images.pexels.com/photos/17483868/pexels-photo-17483868.jpeg",
    tags: [
      "Autonomous Agents",
      "Multi-Agent Systems",
      "Workflow Orchestration",
      "Tool Integration",
      "Memory & Context",
      "Human-in-the-Loop",
    ],
  },
];
